# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('Id_prestamo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Fecha_prestamo', models.DateField(default=django.utils.timezone.now)),
                ('Fecha_devolucion', models.DateField(null=True)),
                ('Persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.Estudiantes')),
                ('recurso', models.ManyToManyField(null=True, to='recursos.Recurso')),
            ],
            options={
                'verbose_name_plural': 'Prestamos',
            },
        ),
    ]
