# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos', '0002_auto_20171006_1651'),
        ('personas', '0002_tipo_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Detalle Prestamos',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Incidencia', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Incidencias',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_prestamo', models.DateField(default=django.utils.timezone.now)),
                ('Fecha_devolucion', models.DateField(null=True)),
                ('ID_Persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.Estudiantes')),
            ],
            options={
                'verbose_name_plural': 'Prestamos',
            },
        ),
        migrations.AddField(
            model_name='detalle_prestamo',
            name='Incidente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.Incidencia'),
        ),
        migrations.AddField(
            model_name='detalle_prestamo',
            name='prestamo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.Prestamo'),
        ),
        migrations.AddField(
            model_name='detalle_prestamo',
            name='recurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos.Recurso'),
        ),
    ]
