# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_incidente',
            options={'verbose_name_plural': 'detalle incidencias'},
        ),
    ]
