# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_remove_detalle_prestamo_incidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_prestamo',
            name='Incidente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.Incidencia'),
        ),
    ]
