# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_auto_20180829_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_incidente',
            old_name='incidente',
            new_name='Incidente',
        ),
    ]
