# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_auto_20180607_1017'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prestamos', '0002_auto_20180607_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('Id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_devolucion', models.DateField(auto_now=True)),
                ('Prestamo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.Prestamo')),
                ('Recurso_devolucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos.Recurso')),
                ('Usuario_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
