# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_auto_20180903_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detalle_Incidente',
            new_name='DetalleIncidente',
        ),
    ]
