# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20180612_1757'),
        ('prestamos', '0003_devolucion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucion',
            options={'verbose_name_plural': 'Devoluciones'},
        ),
        migrations.AddField(
            model_name='incidente',
            name='Persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.Personas'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='Fecha_devolucion',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
