# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 02:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prestamos', '0004_auto_20180903_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleincidente',
            name='Fecha_devolucion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='detalleincidente',
            name='Hora_devolucion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleincidente',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
