# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos', '0006_auto_20180614_1146'),
        ('prestamos', '0004_auto_20180612_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_prestamo',
            fields=[
                ('Id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(choices=[('EN CURSO', 'EN CURSO'), ('EN REVISION', 'EN REVISION'), ('DEVUELTO', 'DEVUELTO')], default='EN CURSO', max_length=20)),
                ('Fecha_devolucion', models.DateField(auto_now=True, null=True)),
                ('Prestamo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.Prestamo')),
                ('Recurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos.Recurso')),
                ('Usuario_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Detalle_prestamo',
            },
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='Prestamo',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='Recurso_devolucion',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='Usuario_devolucion',
        ),
        migrations.DeleteModel(
            name='Devolucion',
        ),
    ]
