# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_auto_20180903_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleincidente',
            old_name='Fecha_devolucion',
            new_name='Fecha',
        ),
        migrations.RenameField(
            model_name='detalleincidente',
            old_name='Hora_devolucion',
            new_name='Hora',
        ),
    ]
