# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_auto_20180614_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='recurso',
        ),
    ]
