# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0006_remove_prestamo_recurso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detalle_prestamo',
            new_name='DetallePrestamo',
        ),
    ]
