# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0008_auto_20180615_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprestamo',
            name='Fecha_prestamo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='detalleprestamo',
            name='Fecha_devolucion',
            field=models.DateField(null=True),
        ),
    ]
