# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0009_auto_20180615_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleprestamo',
            old_name='Recurso',
            new_name='Recurso_detalle',
        ),
    ]
