# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0010_auto_20180618_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprestamo',
            name='Estado',
            field=models.CharField(choices=[('PRESTADO', 'PRESTADO'), ('EN REVISION', 'EN REVISION'), ('DEVUELTO', 'DEVUELTO')], default='PRESTADO', max_length=20),
        ),
    ]
