# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0013_auto_20180618_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprestamo',
            name='Usuario_devolucion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
