# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0014_auto_20180618_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprestamo',
            name='Usuario_devolucion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
