# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 02:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0015_auto_20180618_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprestamo',
            name='Usuario_devolucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
