# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0018_auto_20180620_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='Prestamo',
        ),
        migrations.AddField(
            model_name='incidente',
            name='Prestamo_detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.DetallePrestamo'),
        ),
        migrations.AlterField(
            model_name='detalleprestamo',
            name='Estado',
            field=models.CharField(choices=[('PRESTADO', 'PRESTADO'), ('DEVUELTO', 'DEVUELTO'), ('PERDIDO', 'PERDIDO')], default='PRESTADO', max_length=20),
        ),
    ]
