# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0019_auto_20180621_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='Tipo_Incidente',
            field=models.CharField(choices=[('INCIDENTE TOTAL DEL RECURSO', 'INCIDENTE TOTAL DEL RECURSO'), ('INCIDENTE PARCIAL DEL RECURSO', 'INCIDENTE PARCIAL DEL RECURSO'), ('PERDIDA DEL RECURSO', 'PERDIDA DEL RECURSO'), ('OTRO', 'OTRO')], max_length=50),
        ),
    ]
