# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0020_auto_20180621_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Fecha_prestamo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
