# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0021_auto_20180726_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Fecha_prestamo',
            field=models.DateField(null=True),
        ),
    ]
