# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0022_auto_20180803_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Fecha_prestamo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
