# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Dependencia',
        ),
    ]
