# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('Id_Persona', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Primer_Nombre', models.CharField(max_length=30, null=True)),
                ('Segundo_Nombre', models.CharField(max_length=30, null=True)),
                ('Primer_Apellido', models.CharField(max_length=30, null=True)),
                ('Segundo_Apellido', models.CharField(max_length=30, null=True)),
                ('Nro_Documento', models.CharField(max_length=30)),
                ('Tipo_Documento', models.CharField(choices=[('TI', 'TI'), ('CC', 'CC')], max_length=30)),
                ('Correo_Institucional', models.EmailField(max_length=50, unique=True)),
                ('Nro_Telefonico', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('personas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Personas')),
                ('foto_url', models.URLField(null=True)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=30, null=True)),
                ('Ciclo_Lectivo', models.CharField(max_length=30, null=True)),
                ('Descripcion', models.CharField(max_length=30, null=True)),
                ('Programa_Academico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Programa')),
            ],
            options={
                'verbose_name_plural': 'Estudiantes',
            },
            bases=('personas.personas',),
        ),
    ]
