# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_tipo_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores_Administrativos',
            fields=[
                ('personas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Personas')),
                ('Cargo', models.CharField(max_length=30, null=True)),
                ('Dependencia', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Profesores o Administrativos',
            },
            bases=('personas.personas',),
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='Descripcion',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='foto_url',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='Nro_Telefonico',
        ),
        migrations.AddField(
            model_name='personas',
            name='Codigo_ops',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='Estado_tarjeta',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='Formato_credencial',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='Grupo_acceso',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='Nro_Tarjeta',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='Sede',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='foto_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_persona',
            name='tipo_persona',
            field=models.CharField(choices=[('ESTUDIANTE', 'ESTUDIANTE'), ('PROFESOR O ADMINISTRATIVO', 'PROFESOR O ADMINISTRATIVO')], max_length=30),
        ),
    ]
