# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('Id_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_recurso', models.CharField(max_length=100, null=True)),
                ('Numero_Serie', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia', models.CharField(max_length=100)),
                ('Estado_Recurso', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('EN MANTENIMIENTO', 'EN MANTENIMIENTO'), ('DADO DE BAJA POR PERDIDA', 'DADO DE BAJA POR PERDIDA'), ('DADO DE BAJA POR DA\xd1O TOTAL', 'DADO DE BAJA POR DA\xd1O TOTAL')], default='ACTIVO', max_length=40)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('Marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos.Marca')),
            ],
            options={
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Recurso',
            fields=[
                ('id_recurso', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('tipo_recurso', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo De Recursos',
            },
        ),
        migrations.AddField(
            model_name='recurso',
            name='tipo_de_recurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos.Tipo_Recurso'),
        ),
    ]
