# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='fecha_de_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
