# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_recurso',
            name='id',
        ),
        migrations.AddField(
            model_name='tipo_recurso',
            name='id_recurso',
            field=models.CharField(default='1', max_length=40, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
