# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0008_auto_20180620_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='Estado_Recurso',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('EN MANTENIMIENTO', 'EN MANTENIMIENTO'), ('DADO DE BAJA POR PERDIDA', 'DADO DE BAJA POR PERDIDA'), ('DADO DE BAJA POR DA\xd1O TOTAL', 'DADO DE BAJA POR DA\xd1O TOTAL')], default='ACTIVO', max_length=40),
        ),
    ]
