# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_prestamo',
            name='Incidente',
        ),
    ]
