# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('Nro_Tarjeta', models.CharField(max_length=10, unique=True)),
                ('Id_Persona', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Primer_Nombre', models.CharField(max_length=30, null=True)),
                ('Segundo_Nombre', models.CharField(max_length=30, null=True)),
                ('Primer_Apellido', models.CharField(max_length=30, null=True)),
                ('Segundo_Apellido', models.CharField(max_length=30, null=True)),
                ('Tipo_Documento', models.CharField(choices=[('TI', 'TI'), ('CC', 'CC')], max_length=30)),
                ('Nro_Documento', models.CharField(max_length=30)),
                ('Sede', models.CharField(choices=[('Apartado', 'Apartado'), ('Arauca', 'Arauca'), ('Barrancabermeja', 'Barrancabermeja'), ('Bogota', 'Bogota'), ('Bucaramanga', 'Bucaramanga'), ('Cali', 'Cali'), ('Monteria', 'Monteria'), ('Medellin', 'Medellin')], max_length=30, null=True)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=30, null=True)),
                ('Correo_Institucional', models.EmailField(max_length=50, unique=True)),
                ('Estado_tarjeta', models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('INACTIVA', 'INACTIVA')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('personas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Personas')),
                ('Ciclo_Lectivo', models.CharField(max_length=30, null=True)),
                ('Programa_Academico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Programa')),
            ],
            options={
                'verbose_name_plural': 'Estudiantes',
            },
            bases=('personas.personas',),
        ),
        migrations.CreateModel(
            name='Profesores_Administrativos',
            fields=[
                ('personas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Personas')),
                ('Cargo', models.CharField(max_length=30, null=True)),
                ('Dependencia', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Profesores o Administrativos',
            },
            bases=('personas.personas',),
        ),
    ]
