# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('Nro_Tarjeta', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Id_Persona', models.CharField(max_length=10, unique=True)),
                ('Primer_Nombre', models.CharField(max_length=30, null=True)),
                ('Segundo_Nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('Primer_Apellido', models.CharField(max_length=30, null=True)),
                ('Segundo_Apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('Tipo_Documento', models.CharField(choices=[('TI', 'TI'), ('CC', 'CC')], max_length=30)),
                ('Nro_Documento', models.CharField(max_length=30, unique=True)),
                ('Sede', models.CharField(choices=[('Apartado', 'Apartado'), ('Arauca', 'Arauca'), ('Barrancabermeja', 'Barrancabermeja'), ('Bogota', 'Bogota'), ('Bucaramanga', 'Bucaramanga'), ('Cali', 'Cali'), ('Monteria', 'Monteria'), ('Medellin', 'Medellin')], max_length=30, null=True)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=30, null=True)),
                ('Correo_Institucional', models.EmailField(max_length=50, unique=True)),
                ('Estado_tarjeta', models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('INACTIVA', 'INACTIVA')], max_length=30, null=True)),
                ('Tipo_Persona', models.CharField(choices=[('ESTUDIANTE', 'ESTUDIANTE'), ('ADM O PROFESOR', 'ADM O PROFESOR')], max_length=30, null=True)),
                ('Ciclo_Lectivo', models.CharField(max_length=30, null=True)),
                ('Cargo', models.ManyToManyField(blank=True, to='configuracion.Cargo')),
                ('Dependencias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Dependencia')),
                ('Programa_Academico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Programa')),
            ],
        ),
    ]
