# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('ESTUDIANTE', 'ESTUDIANTE'), ('PROFESOR', 'PROFESOR'), ('ADMINISTRATIVO', 'ADMINISTRATIVO')], max_length=30)),
                ('Id_Persona', models.CharField(max_length=30)),
            ],
        ),
    ]
