# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='Id_Persona',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
