# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20180604_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='Id_Persona',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
