# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20180607_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personas',
            options={'verbose_name_plural': 'Personas'},
        ),
    ]
