# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20180320_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='Sede',
            field=models.CharField(choices=[('Apartado', 'Apartado'), ('Arauca', 'Arauca'), ('Barrancabermeja', 'Barrancabermeja'), ('Bogota', 'Bogota'), ('Bucaramanga', 'Bucaramanga'), ('Cali', 'Cali'), ('Monteria', 'Monteria'), ('Medellin', 'Medellin')], max_length=30, null=True),
        ),
    ]
