# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20180612_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoAcceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_persona', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='personas',
            old_name='Programa_Academico',
            new_name='Dependencia',
        ),
        migrations.RenameField(
            model_name='personas',
            old_name='Estado_tarjeta',
            new_name='Estado_Tarjeta',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='Ciclo_Lectivo',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='Correo_Institucional',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='Id_Persona',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='Primer_Apellido',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='Primer_Nombre',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='Sede',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='Segundo_Apellido',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='Segundo_Nombre',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='Tipo_Documento',
        ),
        migrations.RemoveField(
            model_name='personas',
            name='genero',
        ),
        migrations.AddField(
            model_name='personas',
            name='Apellidos',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='Nombres',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='Tipo_Persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.TipoPersona'),
        ),
        migrations.AddField(
            model_name='personas',
            name='Codigo_Acceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.CodigoAcceso'),
        ),
    ]
