# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_auto_20180817_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='Apellidos',
            field=models.CharField(default='hola', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personas',
            name='Estado_Tarjeta',
            field=models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('INACTIVA', 'INACTIVA')], default='ACTIVO', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personas',
            name='Nombres',
            field=models.CharField(default='JUAN', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personas',
            name='Nro_Documento',
            field=models.CharField(max_length=80),
        ),
    ]
